// Supabase Database Type Definitions for Deshal ERP

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name_ar: string;
          name_en: string | null;
          cr_number: string | null;
          tax_number: string | null;
          logo_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name_ar: string;
          name_en?: string | null;
          cr_number?: string | null;
          tax_number?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name_ar?: string;
          name_en?: string | null;
          cr_number?: string | null;
          tax_number?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      work_centers: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          code: string;
          name: string;
          description: string | null;
          hourly_cost: number;
          capacity_per_hour: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          code: string;
          name: string;
          description?: string | null;
          hourly_cost?: number;
          capacity_per_hour?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          code?: string;
          name?: string;
          description?: string | null;
          hourly_cost?: number;
          capacity_per_hour?: number;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      boms: {
        Row: {
          id: string;
          company_id: string;
          product_id: string;
          code: string;
          name: string;
          description: string | null;
          version: number;
          output_quantity: number;
          scrap_percentage: number;
          status: 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';
          is_default: boolean;
          effective_from: string | null;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          product_id: string;
          code: string;
          name: string;
          description?: string | null;
          version?: number;
          output_quantity?: number;
          scrap_percentage?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';
          is_default?: boolean;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          product_id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          version?: number;
          output_quantity?: number;
          scrap_percentage?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';
          is_default?: boolean;
          effective_from?: string | null;
          effective_to?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
      };
      bom_components: {
        Row: {
          id: string;
          bom_id: string;
          component_product_id: string;
          quantity: number;
          scrap_percentage: number;
          sequence: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bom_id: string;
          component_product_id: string;
          quantity: number;
          scrap_percentage?: number;
          sequence?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bom_id?: string;
          component_product_id?: string;
          quantity?: number;
          scrap_percentage?: number;
          sequence?: number;
          notes?: string | null;
          updated_at?: string;
        };
      };
      production_routings: {
        Row: {
          id: string;
          company_id: string;
          bom_id: string;
          work_center_id: string;
          sequence: number;
          operation_name: string;
          description: string | null;
          setup_minutes: number;
          run_minutes_per_unit: number;
          expected_cost_per_unit: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bom_id: string;
          work_center_id: string;
          sequence?: number;
          operation_name: string;
          description?: string | null;
          setup_minutes?: number;
          run_minutes_per_unit?: number;
          expected_cost_per_unit?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bom_id?: string;
          work_center_id?: string;
          sequence?: number;
          operation_name?: string;
          description?: string | null;
          setup_minutes?: number;
          run_minutes_per_unit?: number;
          expected_cost_per_unit?: number;
          updated_at?: string;
        };
      };
      work_orders: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          project_id: string | null;
          bom_id: string;
          product_id: string;
          source_warehouse_id: string;
          destination_warehouse_id: string;
          work_order_number: string;
          status: 'DRAFT' | 'RELEASED' | 'IN_PROGRESS' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
          planned_quantity: number;
          completed_quantity: number;
          rejected_quantity: number;
          planned_start_date: string | null;
          planned_end_date: string | null;
          actual_start_at: string | null;
          actual_completed_at: string | null;
          material_cost: number;
          labor_cost: number;
          overhead_cost: number;
          total_production_cost: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          project_id?: string | null;
          bom_id: string;
          product_id: string;
          source_warehouse_id: string;
          destination_warehouse_id: string;
          work_order_number: string;
          status?: 'DRAFT' | 'RELEASED' | 'IN_PROGRESS' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
          planned_quantity: number;
          completed_quantity?: number;
          rejected_quantity?: number;
          planned_start_date?: string | null;
          planned_end_date?: string | null;
          actual_start_at?: string | null;
          actual_completed_at?: string | null;
          material_cost?: number;
          labor_cost?: number;
          overhead_cost?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          project_id?: string | null;
          bom_id?: string;
          product_id?: string;
          source_warehouse_id?: string;
          destination_warehouse_id?: string;
          work_order_number?: string;
          status?: 'DRAFT' | 'RELEASED' | 'IN_PROGRESS' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
          planned_quantity?: number;
          completed_quantity?: number;
          rejected_quantity?: number;
          planned_start_date?: string | null;
          planned_end_date?: string | null;
          actual_start_at?: string | null;
          actual_completed_at?: string | null;
          material_cost?: number;
          labor_cost?: number;
          overhead_cost?: number;
          notes?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
      };
      work_order_materials: {
        Row: {
          id: string;
          work_order_id: string;
          component_product_id: string;
          required_quantity: number;
          issued_quantity: number;
          returned_quantity: number;
          unit_cost: number;
          total_cost: number;
          inventory_transaction_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          component_product_id: string;
          required_quantity: number;
          issued_quantity?: number;
          returned_quantity?: number;
          unit_cost?: number;
          inventory_transaction_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          component_product_id?: string;
          required_quantity?: number;
          issued_quantity?: number;
          returned_quantity?: number;
          unit_cost?: number;
          inventory_transaction_id?: string | null;
          updated_at?: string;
        };
      };
      work_order_operations: {
        Row: {
          id: string;
          work_order_id: string;
          routing_id: string | null;
          work_center_id: string;
          sequence: number;
          operation_name: string;
          status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED';
          planned_minutes: number;
          actual_minutes: number;
          hourly_cost: number;
          operation_cost: number;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          routing_id?: string | null;
          work_center_id: string;
          sequence: number;
          operation_name: string;
          status?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED';
          planned_minutes?: number;
          actual_minutes?: number;
          hourly_cost?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          routing_id?: string | null;
          work_center_id?: string;
          sequence?: number;
          operation_name?: string;
          status?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED';
          planned_minutes?: number;
          actual_minutes?: number;
          hourly_cost?: number;
          started_at?: string | null;
          completed_at?: string | null;
          updated_at?: string;
        };
      };
      production_outputs: {
        Row: {
          id: string;
          work_order_id: string;
          product_id: string;
          warehouse_id: string;
          quantity: number;
          unit_cost: number;
          inventory_transaction_id: string | null;
          produced_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          product_id: string;
          warehouse_id: string;
          quantity: number;
          unit_cost?: number;
          inventory_transaction_id?: string | null;
          produced_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          product_id?: string;
          warehouse_id?: string;
          quantity?: number;
          unit_cost?: number;
          inventory_transaction_id?: string | null;
          produced_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          department_id: string | null;
          customer_id: string | null;
          project_manager_id: string | null;
          cost_center_id: string | null;
          project_code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          status: 'DRAFT' | 'PLANNED' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CLOSED' | 'CANCELLED';
          priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
          start_date: string | null;
          planned_end_date: string | null;
          actual_end_date: string | null;
          estimated_cost: number;
          estimated_revenue: number;
          committed_cost: number;
          actual_cost: number;
          actual_revenue: number;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          department_id?: string | null;
          customer_id?: string | null;
          project_manager_id?: string | null;
          cost_center_id?: string | null;
          project_code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'DRAFT' | 'PLANNED' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CLOSED' | 'CANCELLED';
          priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
          start_date?: string | null;
          planned_end_date?: string | null;
          actual_end_date?: string | null;
          estimated_cost?: number;
          estimated_revenue?: number;
          committed_cost?: number;
          actual_cost?: number;
          actual_revenue?: number;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          department_id?: string | null;
          customer_id?: string | null;
          project_manager_id?: string | null;
          cost_center_id?: string | null;
          project_code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'DRAFT' | 'PLANNED' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CLOSED' | 'CANCELLED';
          priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
          start_date?: string | null;
          planned_end_date?: string | null;
          actual_end_date?: string | null;
          estimated_cost?: number;
          estimated_revenue?: number;
          committed_cost?: number;
          actual_cost?: number;
          actual_revenue?: number;
          notes?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
      };
      project_tasks: {
        Row: {
          id: string;
          project_id: string;
          parent_task_id: string | null;
          assigned_employee_id: string | null;
          task_code: string | null;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          status: 'TODO' | 'IN_PROGRESS' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
          priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
          progress_percentage: number;
          estimated_hours: number;
          actual_hours: number;
          estimated_cost: number;
          actual_cost: number;
          start_date: string | null;
          due_date: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          parent_task_id?: string | null;
          assigned_employee_id?: string | null;
          task_code?: string | null;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'TODO' | 'IN_PROGRESS' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
          priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
          progress_percentage?: number;
          estimated_hours?: number;
          actual_hours?: number;
          estimated_cost?: number;
          actual_cost?: number;
          start_date?: string | null;
          due_date?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          parent_task_id?: string | null;
          assigned_employee_id?: string | null;
          task_code?: string | null;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'TODO' | 'IN_PROGRESS' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
          priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
          progress_percentage?: number;
          estimated_hours?: number;
          actual_hours?: number;
          estimated_cost?: number;
          actual_cost?: number;
          start_date?: string | null;
          due_date?: string | null;
          completed_at?: string | null;
          updated_at?: string;
        };
      };
      project_cost_transactions: {
        Row: {
          id: string;
          company_id: string;
          project_id: string;
          project_task_id: string | null;
          cost_center_id: string | null;
          journal_entry_id: string | null;
          journal_entry_line_id: string | null;
          purchase_order_id: string | null;
          transaction_date: string;
          transaction_type: 'DIRECT_COST' | 'LABOR' | 'MATERIAL' | 'EQUIPMENT' | 'SUBCONTRACT' | 'OVERHEAD' | 'OTHER';
          source_type: 'MANUAL' | 'JOURNAL_ENTRY' | 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'PAYROLL' | 'OTHER';
          reference_number: string | null;
          description_ar: string | null;
          description_en: string | null;
          amount: number;
          status: 'DRAFT' | 'POSTED' | 'VOIDED';
          created_by: string | null;
          created_at: string;
          posted_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          project_id: string;
          project_task_id?: string | null;
          cost_center_id?: string | null;
          journal_entry_id?: string | null;
          journal_entry_line_id?: string | null;
          purchase_order_id?: string | null;
          transaction_date?: string;
          transaction_type?: 'DIRECT_COST' | 'LABOR' | 'MATERIAL' | 'EQUIPMENT' | 'SUBCONTRACT' | 'OVERHEAD' | 'OTHER';
          source_type?: 'MANUAL' | 'JOURNAL_ENTRY' | 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'PAYROLL' | 'OTHER';
          reference_number?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          amount: number;
          status?: 'DRAFT' | 'POSTED' | 'VOIDED';
          created_by?: string | null;
          created_at?: string;
          posted_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          project_id?: string;
          project_task_id?: string | null;
          cost_center_id?: string | null;
          journal_entry_id?: string | null;
          journal_entry_line_id?: string | null;
          purchase_order_id?: string | null;
          transaction_date?: string;
          transaction_type?: 'DIRECT_COST' | 'LABOR' | 'MATERIAL' | 'EQUIPMENT' | 'SUBCONTRACT' | 'OVERHEAD' | 'OTHER';
          source_type?: 'MANUAL' | 'JOURNAL_ENTRY' | 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'PAYROLL' | 'OTHER';
          reference_number?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          amount?: number;
          status?: 'DRAFT' | 'POSTED' | 'VOIDED';
          created_by?: string | null;
          posted_at?: string | null;
          updated_at?: string;
        };
      };
      project_commitments: {
        Row: {
          id: string;
          company_id: string;
          project_id: string;
          purchase_order_id: string | null;
          reference_number: string | null;
          commitment_date: string;
          description_ar: string | null;
          description_en: string | null;
          amount: number;
          status: 'DRAFT' | 'ACTIVE' | 'FULFILLED' | 'CANCELLED';
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          project_id: string;
          purchase_order_id?: string | null;
          reference_number?: string | null;
          commitment_date?: string;
          description_ar?: string | null;
          description_en?: string | null;
          amount: number;
          status?: 'DRAFT' | 'ACTIVE' | 'FULFILLED' | 'CANCELLED';
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          project_id?: string;
          purchase_order_id?: string | null;
          reference_number?: string | null;
          commitment_date?: string;
          description_ar?: string | null;
          description_en?: string | null;
          amount?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'FULFILLED' | 'CANCELLED';
          created_by?: string | null;
          updated_at?: string;
        };
      };
      project_revenue_transactions: {
        Row: {
          id: string;
          company_id: string;
          project_id: string;
          invoice_id: string | null;
          journal_entry_id: string | null;
          transaction_date: string;
          source_type: 'MANUAL' | 'INVOICE' | 'JOURNAL_ENTRY' | 'SALES_ORDER' | 'OTHER';
          reference_number: string | null;
          description_ar: string | null;
          description_en: string | null;
          amount: number;
          status: 'DRAFT' | 'POSTED' | 'VOIDED';
          created_by: string | null;
          created_at: string;
          posted_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          project_id: string;
          invoice_id?: string | null;
          journal_entry_id?: string | null;
          transaction_date?: string;
          source_type?: 'MANUAL' | 'INVOICE' | 'JOURNAL_ENTRY' | 'SALES_ORDER' | 'OTHER';
          reference_number?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          amount: number;
          status?: 'DRAFT' | 'POSTED' | 'VOIDED';
          created_by?: string | null;
          created_at?: string;
          posted_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          project_id?: string;
          invoice_id?: string | null;
          journal_entry_id?: string | null;
          transaction_date?: string;
          source_type?: 'MANUAL' | 'INVOICE' | 'JOURNAL_ENTRY' | 'SALES_ORDER' | 'OTHER';
          reference_number?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          amount?: number;
          status?: 'DRAFT' | 'POSTED' | 'VOIDED';
          created_by?: string | null;
          posted_at?: string | null;
          updated_at?: string;
        };
      };
      budgets: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          fiscal_year: number;
          code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          currency: string;
          status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
          start_date: string;
          end_date: string;
          total_budget_amount: number;
          total_committed_amount: number;
          total_actual_amount: number;
          created_by: string | null;
          submitted_by: string | null;
          approved_by: string | null;
          submitted_at: string | null;
          approved_at: string | null;
          activated_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          fiscal_year: number;
          code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          currency?: string;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
          start_date: string;
          end_date: string;
          total_budget_amount?: number;
          total_committed_amount?: number;
          total_actual_amount?: number;
          created_by?: string | null;
          submitted_by?: string | null;
          approved_by?: string | null;
          submitted_at?: string | null;
          approved_at?: string | null;
          activated_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          fiscal_year?: number;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          currency?: string;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
          start_date?: string;
          end_date?: string;
          total_budget_amount?: number;
          total_committed_amount?: number;
          total_actual_amount?: number;
          created_by?: string | null;
          submitted_by?: string | null;
          approved_by?: string | null;
          submitted_at?: string | null;
          approved_at?: string | null;
          activated_at?: string | null;
          closed_at?: string | null;
          updated_at?: string;
        };
      };
      budget_versions: {
        Row: {
          id: string;
          budget_id: string;
          version_number: number;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED' | 'CLOSED' | 'CANCELLED';
          is_current: boolean;
          total_amount: number;
          created_by: string | null;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          budget_id: string;
          version_number: number;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED' | 'CLOSED' | 'CANCELLED';
          is_current?: boolean;
          total_amount?: number;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          budget_id?: string;
          version_number?: number;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED' | 'CLOSED' | 'CANCELLED';
          is_current?: boolean;
          total_amount?: number;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          updated_at?: string;
        };
      };
      budget_lines: {
        Row: {
          id: string;
          budget_version_id: string;
          account_id: string;
          branch_id: string | null;
          department_id: string | null;
          cost_center_id: string | null;
          fiscal_period_id: string | null;
          description_ar: string | null;
          description_en: string | null;
          budget_amount: number;
          committed_amount: number;
          actual_amount: number;
          available_amount: number;
          alert_threshold_percentage: number;
          block_overspend: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          budget_version_id: string;
          account_id: string;
          branch_id?: string | null;
          department_id?: string | null;
          cost_center_id?: string | null;
          fiscal_period_id?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          budget_amount?: number;
          committed_amount?: number;
          actual_amount?: number;
          alert_threshold_percentage?: number;
          block_overspend?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          budget_version_id?: string;
          account_id?: string;
          branch_id?: string | null;
          department_id?: string | null;
          cost_center_id?: string | null;
          fiscal_period_id?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          budget_amount?: number;
          committed_amount?: number;
          actual_amount?: number;
          alert_threshold_percentage?: number;
          block_overspend?: boolean;
          updated_at?: string;
        };
      };
      budget_commitments: {
        Row: {
          id: string;
          company_id: string;
          budget_line_id: string;
          source_type: 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'ASSET' | 'PAYROLL' | 'MANUAL' | 'OTHER';
          source_id: string | null;
          commitment_number: string;
          commitment_date: string;
          amount: number;
          released_amount: number;
          status: 'DRAFT' | 'ACTIVE' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'CANCELLED';
          description_ar: string | null;
          description_en: string | null;
          created_by: string | null;
          released_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          budget_line_id: string;
          source_type: 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'ASSET' | 'PAYROLL' | 'MANUAL' | 'OTHER';
          source_id?: string | null;
          commitment_number: string;
          commitment_date?: string;
          amount: number;
          released_amount?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'CANCELLED';
          description_ar?: string | null;
          description_en?: string | null;
          created_by?: string | null;
          released_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          budget_line_id?: string;
          source_type?: 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'ASSET' | 'PAYROLL' | 'MANUAL' | 'OTHER';
          source_id?: string | null;
          commitment_number?: string;
          commitment_date?: string;
          amount?: number;
          released_amount?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'CANCELLED';
          description_ar?: string | null;
          description_en?: string | null;
          created_by?: string | null;
          released_at?: string | null;
          cancelled_at?: string | null;
          updated_at?: string;
        };
      };
      budget_actual_transactions: {
        Row: {
          id: string;
          company_id: string;
          budget_line_id: string;
          journal_entry_id: string;
          journal_entry_line_id: string;
          transaction_date: string;
          amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          budget_line_id: string;
          journal_entry_id: string;
          journal_entry_line_id: string;
          transaction_date: string;
          amount: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          budget_line_id?: string;
          journal_entry_id?: string;
          journal_entry_line_id?: string;
          transaction_date?: string;
          amount?: number;
        };
      };
      user_workspace_preferences: {
        Row: {
          id: string;
          user_id: string;
          user_email: string | null;
          config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_email?: string | null;
          config: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_email?: string | null;
          config?: Json;
          updated_at?: string;
        };
      };
    };
    Views: {
      v_work_order_costing: {
        Row: {
          work_order_id: string;
          company_id: string;
          work_order_number: string;
          status: string;
          product_id: string;
          planned_quantity: number;
          completed_quantity: number;
          material_cost: number;
          labor_cost: number;
          overhead_cost: number;
          total_production_cost: number;
          actual_unit_cost: number;
          production_health: 'ON_TARGET' | 'UNDER_PRODUCTION' | 'IN_PROGRESS' | 'PENDING';
        };
      };
      v_bom_material_requirements: {
        Row: {
          bom_id: string;
          company_id: string;
          finished_product_id: string;
          output_quantity: number;
          component_product_id: string;
          quantity: number;
          scrap_percentage: number;
          effective_component_quantity: number;
        };
      };
      v_project_profitability: {
        Row: {
          project_id: string;
          company_id: string;
          project_code: string;
          name_ar: string;
          name_en: string | null;
          status: string;
          customer_id: string | null;
          project_manager_id: string | null;
          cost_center_id: string | null;
          start_date: string | null;
          planned_end_date: string | null;
          actual_end_date: string | null;
          estimated_cost: number;
          estimated_revenue: number;
          committed_cost: number;
          actual_cost: number;
          actual_revenue: number;
          gross_profit: number;
          profit_margin_percentage: number;
          estimated_profit: number;
          estimated_profit_margin_percentage: number;
          cost_variance: number;
          revenue_variance: number;
          cost_health: 'NORMAL' | 'WARNING' | 'OVER_BUDGET';
        };
      };
      v_project_task_progress: {
        Row: {
          project_id: string;
          company_id: string;
          project_code: string;
          project_name_ar: string;
          project_name_en: string | null;
          total_tasks: number;
          completed_tasks: number;
          in_progress_tasks: number;
          on_hold_tasks: number;
          average_progress_percentage: number;
          task_estimated_cost: number;
          task_actual_cost: number;
        };
      };
      v_budget_vs_actual: {
        Row: {
          budget_id: string;
          company_id: string;
          budget_branch_id: string | null;
          budget_code: string;
          budget_name_ar: string;
          budget_name_en: string | null;
          fiscal_year: number;
          budget_status: string;
          budget_version_id: string;
          version_number: number;
          is_current: boolean;
          budget_line_id: string;
          account_id: string;
          account_code: string;
          account_name_ar: string;
          account_name_en: string | null;
          branch_id: string | null;
          department_id: string | null;
          cost_center_id: string | null;
          fiscal_period_id: string | null;
          budget_amount: number;
          committed_amount: number;
          actual_amount: number;
          available_amount: number;
          utilization_percentage: number;
          budget_health: 'NORMAL' | 'WARNING' | 'OVER_BUDGET';
        };
      };
    };
    Functions: {
      auth_user_company_ids: {
        Args: Record<PropertyKey, never>;
        Returns: string[];
      };
      auth_user_has_permission: {
        Args: { p_permission: string };
        Returns: boolean;
      };
      sync_project_financial_totals: {
        Args: { p_project_id: string };
        Returns: void;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
