// Supabase Database Type Definitions for Deshal ERP

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name_ar: string;
          name_en: string | null;
          cr_number: string | null;
          tax_number: string | null;
          logo_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name_ar: string;
          name_en?: string | null;
          cr_number?: string | null;
          tax_number?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name_ar?: string;
          name_en?: string | null;
          cr_number?: string | null;
          tax_number?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      budgets: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          fiscal_year: number;
          code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          currency: string;
          status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
          start_date: string;
          end_date: string;
          total_budget_amount: number;
          total_committed_amount: number;
          total_actual_amount: number;
          created_by: string | null;
          submitted_by: string | null;
          approved_by: string | null;
          submitted_at: string | null;
          approved_at: string | null;
          activated_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          fiscal_year: number;
          code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          currency?: string;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
          start_date: string;
          end_date: string;
          total_budget_amount?: number;
          total_committed_amount?: number;
          total_actual_amount?: number;
          created_by?: string | null;
          submitted_by?: string | null;
          approved_by?: string | null;
          submitted_at?: string | null;
          approved_at?: string | null;
          activated_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          fiscal_year?: number;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          currency?: string;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
          start_date?: string;
          end_date?: string;
          total_budget_amount?: number;
          total_committed_amount?: number;
          total_actual_amount?: number;
          created_by?: string | null;
          submitted_by?: string | null;
          approved_by?: string | null;
          submitted_at?: string | null;
          approved_at?: string | null;
          activated_at?: string | null;
          closed_at?: string | null;
          updated_at?: string;
        };
      };
      budget_versions: {
        Row: {
          id: string;
          budget_id: string;
          version_number: number;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED' | 'CLOSED' | 'CANCELLED';
          is_current: boolean;
          total_amount: number;
          created_by: string | null;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          budget_id: string;
          version_number: number;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED' | 'CLOSED' | 'CANCELLED';
          is_current?: boolean;
          total_amount?: number;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          budget_id?: string;
          version_number?: number;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          status?: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED' | 'CLOSED' | 'CANCELLED';
          is_current?: boolean;
          total_amount?: number;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          updated_at?: string;
        };
      };
      budget_lines: {
        Row: {
          id: string;
          budget_version_id: string;
          account_id: string;
          branch_id: string | null;
          department_id: string | null;
          cost_center_id: string | null;
          fiscal_period_id: string | null;
          description_ar: string | null;
          description_en: string | null;
          budget_amount: number;
          committed_amount: number;
          actual_amount: number;
          available_amount: number;
          alert_threshold_percentage: number;
          block_overspend: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          budget_version_id: string;
          account_id: string;
          branch_id?: string | null;
          department_id?: string | null;
          cost_center_id?: string | null;
          fiscal_period_id?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          budget_amount?: number;
          committed_amount?: number;
          actual_amount?: number;
          alert_threshold_percentage?: number;
          block_overspend?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          budget_version_id?: string;
          account_id?: string;
          branch_id?: string | null;
          department_id?: string | null;
          cost_center_id?: string | null;
          fiscal_period_id?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          budget_amount?: number;
          committed_amount?: number;
          actual_amount?: number;
          alert_threshold_percentage?: number;
          block_overspend?: boolean;
          updated_at?: string;
        };
      };
      budget_commitments: {
        Row: {
          id: string;
          company_id: string;
          budget_line_id: string;
          source_type: 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'ASSET' | 'PAYROLL' | 'MANUAL' | 'OTHER';
          source_id: string | null;
          commitment_number: string;
          commitment_date: string;
          amount: number;
          released_amount: number;
          status: 'DRAFT' | 'ACTIVE' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'CANCELLED';
          description_ar: string | null;
          description_en: string | null;
          created_by: string | null;
          released_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          budget_line_id: string;
          source_type: 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'ASSET' | 'PAYROLL' | 'MANUAL' | 'OTHER';
          source_id?: string | null;
          commitment_number: string;
          commitment_date?: string;
          amount: number;
          released_amount?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'CANCELLED';
          description_ar?: string | null;
          description_en?: string | null;
          created_by?: string | null;
          released_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          budget_line_id?: string;
          source_type?: 'PURCHASE_ORDER' | 'SUPPLIER_INVOICE' | 'ASSET' | 'PAYROLL' | 'MANUAL' | 'OTHER';
          source_id?: string | null;
          commitment_number?: string;
          commitment_date?: string;
          amount?: number;
          released_amount?: number;
          status?: 'DRAFT' | 'ACTIVE' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'CANCELLED';
          description_ar?: string | null;
          description_en?: string | null;
          created_by?: string | null;
          released_at?: string | null;
          cancelled_at?: string | null;
          updated_at?: string;
        };
      };
      budget_actual_transactions: {
        Row: {
          id: string;
          company_id: string;
          budget_line_id: string;
          journal_entry_id: string;
          journal_entry_line_id: string;
          transaction_date: string;
          amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          budget_line_id: string;
          journal_entry_id: string;
          journal_entry_line_id: string;
          transaction_date: string;
          amount: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          budget_line_id?: string;
          journal_entry_id?: string;
          journal_entry_line_id?: string;
          transaction_date?: string;
          amount?: number;
        };
      };
      asset_categories: {
        Row: {
          id: string;
          company_id: string;
          code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          asset_account_id: string;
          accumulated_depreciation_account_id: string;
          depreciation_expense_account_id: string;
          gain_on_disposal_account_id: string | null;
          loss_on_disposal_account_id: string | null;
          default_useful_life_months: number | null;
          default_depreciation_method: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
          default_salvage_percentage: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          asset_account_id: string;
          accumulated_depreciation_account_id: string;
          depreciation_expense_account_id: string;
          gain_on_disposal_account_id?: string | null;
          loss_on_disposal_account_id?: string | null;
          default_useful_life_months?: number | null;
          default_depreciation_method?: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
          default_salvage_percentage?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          asset_account_id?: string;
          accumulated_depreciation_account_id?: string;
          depreciation_expense_account_id?: string;
          gain_on_disposal_account_id?: string | null;
          loss_on_disposal_account_id?: string | null;
          default_useful_life_months?: number | null;
          default_depreciation_method?: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
          default_salvage_percentage?: number;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      fixed_assets: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          category_id: string;
          cost_center_id: string | null;
          asset_code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          serial_number: string | null;
          barcode: string | null;
          acquisition_date: string;
          capitalization_date: string;
          depreciation_start_date: string | null;
          original_cost: number;
          salvage_value: number;
          accumulated_depreciation: number;
          net_book_value: number;
          useful_life_months: number;
          depreciation_method: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
          declining_balance_rate: number | null;
          currency: string;
          status: 'DRAFT' | 'ACTIVE' | 'FULLY_DEPRECIATED' | 'DISPOSED' | 'SUSPENDED';
          asset_account_id: string | null;
          accumulated_depreciation_account_id: string | null;
          depreciation_expense_account_id: string | null;
          gain_on_disposal_account_id: string | null;
          loss_on_disposal_account_id: string | null;
          acquisition_journal_entry_id: string | null;
          disposal_journal_entry_id: string | null;
          disposed_at: string | null;
          disposed_by: string | null;
          disposal_notes: string | null;
          metadata: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          category_id: string;
          cost_center_id?: string | null;
          asset_code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          serial_number?: string | null;
          barcode?: string | null;
          acquisition_date: string;
          capitalization_date: string;
          depreciation_start_date?: string | null;
          original_cost: number;
          salvage_value?: number;
          accumulated_depreciation?: number;
          useful_life_months: number;
          depreciation_method?: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
          declining_balance_rate?: number | null;
          currency?: string;
          status?: 'DRAFT' | 'ACTIVE' | 'FULLY_DEPRECIATED' | 'DISPOSED' | 'SUSPENDED';
          asset_account_id?: string | null;
          accumulated_depreciation_account_id?: string | null;
          depreciation_expense_account_id?: string | null;
          gain_on_disposal_account_id?: string | null;
          loss_on_disposal_account_id?: string | null;
          acquisition_journal_entry_id?: string | null;
          disposal_journal_entry_id?: string | null;
          disposed_at?: string | null;
          disposed_by?: string | null;
          disposal_notes?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          category_id?: string;
          cost_center_id?: string | null;
          asset_code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          serial_number?: string | null;
          barcode?: string | null;
          acquisition_date?: string;
          capitalization_date?: string;
          depreciation_start_date?: string | null;
          original_cost?: number;
          salvage_value?: number;
          accumulated_depreciation?: number;
          useful_life_months?: number;
          depreciation_method?: 'STRAIGHT_LINE' | 'DECLINING_BALANCE';
          declining_balance_rate?: number | null;
          currency?: string;
          status?: 'DRAFT' | 'ACTIVE' | 'FULLY_DEPRECIATED' | 'DISPOSED' | 'SUSPENDED';
          asset_account_id?: string | null;
          accumulated_depreciation_account_id?: string | null;
          depreciation_expense_account_id?: string | null;
          gain_on_disposal_account_id?: string | null;
          loss_on_disposal_account_id?: string | null;
          acquisition_journal_entry_id?: string | null;
          disposal_journal_entry_id?: string | null;
          disposed_at?: string | null;
          disposed_by?: string | null;
          disposal_notes?: string | null;
          metadata?: Json;
          created_by?: string | null;
          updated_at?: string;
        };
      };
      asset_depreciation_schedules: {
        Row: {
          id: string;
          company_id: string;
          asset_id: string;
          schedule_date: string;
          fiscal_period_id: string | null;
          opening_book_value: number;
          depreciation_amount: number;
          closing_book_value: number;
          accumulated_depreciation_before: number;
          accumulated_depreciation_after: number;
          status: 'SCHEDULED' | 'POSTED' | 'SKIPPED' | 'CANCELLED';
          journal_entry_id: string | null;
          posted_at: string | null;
          posted_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          asset_id: string;
          schedule_date: string;
          fiscal_period_id?: string | null;
          opening_book_value: number;
          depreciation_amount: number;
          closing_book_value: number;
          accumulated_depreciation_before: number;
          accumulated_depreciation_after: number;
          status?: 'SCHEDULED' | 'POSTED' | 'SKIPPED' | 'CANCELLED';
          journal_entry_id?: string | null;
          posted_at?: string | null;
          posted_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          asset_id?: string;
          schedule_date?: string;
          fiscal_period_id?: string | null;
          opening_book_value?: number;
          depreciation_amount?: number;
          closing_book_value?: number;
          accumulated_depreciation_before?: number;
          accumulated_depreciation_after?: number;
          status?: 'SCHEDULED' | 'POSTED' | 'SKIPPED' | 'CANCELLED';
          journal_entry_id?: string | null;
          posted_at?: string | null;
          posted_by?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
      };
      asset_transfers: {
        Row: {
          id: string;
          company_id: string;
          asset_id: string;
          transfer_number: string;
          from_branch_id: string | null;
          to_branch_id: string | null;
          from_cost_center_id: string | null;
          to_cost_center_id: string | null;
          transfer_date: string;
          status: 'DRAFT' | 'APPROVED' | 'COMPLETED' | 'CANCELLED';
          notes: string | null;
          approved_at: string | null;
          approved_by: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          asset_id: string;
          transfer_number: string;
          from_branch_id?: string | null;
          to_branch_id?: string | null;
          from_cost_center_id?: string | null;
          to_cost_center_id?: string | null;
          transfer_date: string;
          status?: 'DRAFT' | 'APPROVED' | 'COMPLETED' | 'CANCELLED';
          notes?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          asset_id?: string;
          transfer_number?: string;
          from_branch_id?: string | null;
          to_branch_id?: string | null;
          from_cost_center_id?: string | null;
          to_cost_center_id?: string | null;
          transfer_date?: string;
          status?: 'DRAFT' | 'APPROVED' | 'COMPLETED' | 'CANCELLED';
          notes?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
      };
      asset_disposals: {
        Row: {
          id: string;
          company_id: string;
          asset_id: string;
          disposal_number: string;
          disposal_date: string;
          disposal_type: 'SALE' | 'SCRAP' | 'WRITE_OFF' | 'DONATION';
          proceeds_amount: number;
          disposal_expenses: number;
          book_value_at_disposal: number;
          gain_loss_amount: number;
          customer_id: string | null;
          invoice_id: string | null;
          journal_entry_id: string | null;
          status: 'DRAFT' | 'POSTED' | 'CANCELLED';
          notes: string | null;
          posted_at: string | null;
          posted_by: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          asset_id: string;
          disposal_number: string;
          disposal_date: string;
          disposal_type?: 'SALE' | 'SCRAP' | 'WRITE_OFF' | 'DONATION';
          proceeds_amount?: number;
          disposal_expenses?: number;
          book_value_at_disposal?: number;
          gain_loss_amount?: number;
          customer_id?: string | null;
          invoice_id?: string | null;
          journal_entry_id?: string | null;
          status?: 'DRAFT' | 'POSTED' | 'CANCELLED';
          notes?: string | null;
          posted_at?: string | null;
          posted_by?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          asset_id?: string;
          disposal_number?: string;
          disposal_date?: string;
          disposal_type?: 'SALE' | 'SCRAP' | 'WRITE_OFF' | 'DONATION';
          proceeds_amount?: number;
          disposal_expenses?: number;
          book_value_at_disposal?: number;
          gain_loss_amount?: number;
          customer_id?: string | null;
          invoice_id?: string | null;
          journal_entry_id?: string | null;
          status?: 'DRAFT' | 'POSTED' | 'CANCELLED';
          notes?: string | null;
          posted_at?: string | null;
          posted_by?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          company_id: string;
          category_id: string | null;
          document_number: string | null;
          title: string;
          description: string | null;
          file_name: string;
          file_type: string;
          mime_type: string | null;
          file_size: number;
          storage_bucket: string;
          storage_path: string;
          status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED' | 'EXPIRED' | 'LOCKED' | 'DELETED';
          current_version_id: string | null;
          entity_type: string | null;
          entity_id: string | null;
          expires_at: string | null;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          category_id?: string | null;
          document_number?: string | null;
          title: string;
          description?: string | null;
          file_name: string;
          file_type: string;
          mime_type?: string | null;
          file_size: number;
          storage_bucket: string;
          storage_path: string;
          status?: 'DRAFT' | 'ACTIVE' | 'ARCHIVED' | 'EXPIRED' | 'LOCKED' | 'DELETED';
          current_version_id?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          expires_at?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          category_id?: string | null;
          document_number?: string | null;
          title?: string;
          description?: string | null;
          file_name?: string;
          file_type?: string;
          mime_type?: string | null;
          file_size?: number;
          storage_bucket?: string;
          storage_path?: string;
          status?: 'DRAFT' | 'ACTIVE' | 'ARCHIVED' | 'EXPIRED' | 'LOCKED' | 'DELETED';
          current_version_id?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          expires_at?: string | null;
          uploaded_by?: string | null;
          updated_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
      };
    };
    Views: {
      v_budget_vs_actual: {
        Row: {
          budget_id: string;
          company_id: string;
          budget_branch_id: string | null;
          budget_code: string;
          budget_name_ar: string;
          budget_name_en: string | null;
          fiscal_year: number;
          budget_status: string;
          budget_version_id: string;
          version_number: number;
          is_current: boolean;
          budget_line_id: string;
          account_id: string;
          account_code: string;
          account_name_ar: string;
          account_name_en: string | null;
          branch_id: string | null;
          department_id: string | null;
          cost_center_id: string | null;
          fiscal_period_id: string | null;
          budget_amount: number;
          committed_amount: number;
          actual_amount: number;
          available_amount: number;
          utilization_percentage: number;
          budget_health: 'NORMAL' | 'WARNING' | 'OVER_BUDGET';
        };
      };
    };
    Functions: {
      auth_user_company_ids: {
        Args: Record<PropertyKey, never>;
        Returns: string[];
      };
      auth_user_has_permission: {
        Args: { p_permission: string };
        Returns: boolean;
      };
      generate_asset_depreciation_schedule: {
        Args: { p_asset_id: string };
        Returns: number;
      };
      post_asset_depreciation: {
        Args: { p_schedule_id: string };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
